name: debughidevent_build_release_armhf

on:
  push:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'
  pull_request:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'

jobs:
  build_armhf:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set Version
      if: ${{ (startsWith(github.ref, 'refs/tags/v')) }}
      run:  echo "debughideventDVER=$(echo ${GITHUB_REF} | sed 's|refs/heads/||g' | sed 's|refs/tags/v||g' | sed 's|-beta||g' )" >> $GITHUB_ENV  
    - name: set Version
      if: ${{ !(startsWith(github.ref, 'refs/tags/v')) }}
      run:  echo "debughideventDVER=1.0.0-1" >> $GITHUB_ENV  
    - name: set majorVersion
      run:  echo "debughideventDMAJORVER=$(echo $debughideventDVER | sed 's|-.*$||g' | cut -d. -f1 )" >> $GITHUB_ENV  
    - name: set minorVersion
      run:  echo "debughideventDMINORVER=$(echo $debughideventDVER | sed 's|-.*$||g' | cut -d. -f2 )" >> $GITHUB_ENV  
    - name: set patchVersion
      run:  echo "debughideventDPATCHVER=$(echo $debughideventDVER | sed 's|-.*$||g' | cut -d. -f3 )" >> $GITHUB_ENV  
    - name: set version control
      run: 'sed -i "s|Version: .*$|Version: $debughideventDVER|g" DEBIAN/control'

    - name: set majorVersion cmake
      run: 'sed -i "s|^set.*VERSION_MAJOR.*$|set (\${PROJECT_NAME}_VERSION_MAJOR $debughideventDMAJORVER)|g" CMakeLists.txt'
    - name: set minorVersion cmake
      run: 'sed -i "s|^set.*VERSION_MINOR.*$|set (\${PROJECT_NAME}_VERSION_MINOR $debughideventDMINORVER)|g" CMakeLists.txt'
    - name: set patchVersion cmake
      run: 'sed -i "s|^set.*PATCH_LEVEL.*$|set (\${PROJECT_NAME}_PATCH_LEVEL $debughideventDPATCHVER)|g" CMakeLists.txt'

   
    - name: Run armhf build
      uses: pguyot/arm-runner-action@v1
      id: arm_runner_tests
      with:
        image_additional_mb: 4096
        base_image: 'raspios_lite:2021-05-07'
        cpu: 'arm1176'
        optimize_image: no
        copy_artifact_path: 'build/debughidevent_1.0.0_armhf.deb'
        copy_artifact_dest: "./build/"
        commands: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y libconfuse-dev liblo-dev build-essential wget libssl-dev python3 python3-pip 
          sudo python3 -m pip install lastversion
          wget $(lastversion https://github.com/Apfelwurm/cmake-raspberry --assets | grep *armhf*.deb)
          dpkg -i cmake_*_armhf*.deb
          sudo ./rebuild_armhf.sh 


    - name: move armhf build
      run: 'mv build/debughidevent_1.0.0_armhf.deb $(echo "build/debughidevent_"$debughideventDVER"_armhf.deb")'


    - name: make release
      if: ${{ (startsWith(github.ref, 'refs/tags/v')) && (!(contains(github.ref, '-beta'))) }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./build/debughidevent_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    - name: make release
      if: ${{ (startsWith(github.ref, 'refs/tags/v')) && ((contains(github.ref, '-beta'))) }}
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: |
          ./build/debughidevent_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
